### ISSUE TITLE
[Modal UI] 진행중인 투표 - 투표 항목 개수 늘어나면 깨짐

### ISSUE THREAD

**Issue by kjy2844** [sparcs-kaist/biseo#170]
<img width="713" alt="스크린샷 2023-08-25 오후 1 01 03" src="https://github.com/sparcs-kaist/biseo/assets/47997136/5974516d-b37b-41ae-8606-4f5522ff4f94">

**Comment by minjoo0729** [comment]
**Slack [디자인 issue - 투표 항목 깨짐 현상]**
https://sparcs.slack.com/archives/C01RC6QMSL8/p1695137123735969
