### ISSUE TITLE
[투표 생성 모달] 투표 항목이 길어지면 UI 깨짐

### ISSUE THREAD

**Issue by kjy2844** [sparcs-kaist/biseo#182]
<img width="338" alt="스크린샷 2023-08-25 오후 8 39 45" src="https://github.com/sparcs-kaist/biseo/assets/47997136/23bcf1d2-ef8e-4a6a-ae83-e33ec67a6de9">

**Comment by kjy2844** [comment]
현재는 이렇게 깨지네요
<img width="609" alt="스크린샷 2023-08-26 오전 11 54 45" src="https://github.com/sparcs-kaist/biseo/assets/47997136/e820b1d3-b184-413d-a336-3c3237595b52">

**Comment by minjoo0729** [comment]
영어의 경우에는 가로로 계속 늘어나는 것 같습니다
<img width="239" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/114305937/83cb63b8-c97d-49a4-b7b5-3212bf61ed27">

**Comment by minjoo0729** [comment]
**Slack [디자인 issue - 투표 항목 깨짐 현상]**
https://sparcs.slack.com/archives/C01RC6QMSL8/p1695137123735969
