### ISSUE TITLE
[채팅] ChatInput.tsx - onKeyPress is deprecated

### ISSUE THREAD

**Issue by babycroc** [sparcs-kaist/biseo#195]

**Comment by babycroc** [comment]
#199 참고

**Comment by SnowSuno** [comment]
이거의 대안으로들 많이 쓰는 `onKeyDown`, `onKeyUp`, `beforeInput`은 모두 `onKeyPress`와 behavior가 약간씩 달라서 이거로 대체할 경우 한글 입력에서 마지막 글자가 깨지는 이슈 발생
