### ISSUE TITLE
[투표 모달 UI] 버튼들이 찌뿌됐어요..

### ISSUE THREAD

**Issue by babycroc** [sparcs-kaist/biseo#221]
<img width="699" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/33417582/262755d1-8169-441f-b6c9-fb09dbe47a38">
<img width="702" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/33417582/635d4764-12c6-4923-87eb-dd1b631f0ae8">
<img width="699" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/33417582/56c805e2-66cd-49c7-8d7a-4b6595aef239">

**Comment by prectal123** [comment]
해결해볼게요
