### ISSUE TITLE
[채팅] 글이 아주 길어서 입력창이 채팅창을 가득 채우는 경우 스크롤 불가 & 채팅에 입력이 안됨

### ISSUE THREAD

**Issue by jinhyeonkwon** [sparcs-kaist/biseo#228]
채팅 글자 제한이 있는지는 모르는 채로 남깁니다!

![image](https://github.com/sparcs-kaist/biseo/assets/121283722/4e1adf95-fc6f-4266-b347-6345b96cf130)

**Comment by JeukHwang** [comment]
글자 수를 제한하는 방법과 이를 UI에서 보여주는 방법에 대해 논의하는 #309가,
글자 수 미제한으로 인한 스크롤 불가와 채팅 전송 불가 문제를 다루는 본 이슈가 관련되어 있습니다.

채팅 전송 불가의 경우, 백엔드 제한에 맞추어 프론트엔드를 수정하여 해결될 것으로 예상됩니다.
스크롤 불가의 경우 채팅의 form tag에 max-height와 scroll 관련 css를 추가하여 해결될 것으로 예상됩니다.

개강총회에서 관련된 수정이 일어났다고 알고 있는데, 구체적인 사항을 알지 못해 제가 해결하기 어려울 것 같습니다.
관련된 분들을 멘션합니다. @minjoo0729 @SnowSuno

**Comment by jinhyeonkwon** [comment]
현재 배포판으로 다시 실험해본 결과, 스크롤이 뜨긴 하는데 채팅 입력창의 높이가 전체 채팅창의 높이를 넘어서야 스크롤 바가 발생하는 것 같습니다. (즉 일정 길이 이상에서는 여전히 전송 버튼을 누를 수 없습니다) 말씀해주신 사항에 맞추어 추가 수정을 진행한다면 해결될 것으로 예상합니다.
