### ISSUE TITLE
[투표 생성] 1920 1080 모니터에서 투표 생성하기 버튼 텍스트 배치가 이상함 & 투표 대상 전체 선택 버튼과 투표 결과, 투표 상세 버튼, 태그 선택 버튼 미동작

### ISSUE THREAD

**Issue by jinhyeonkwon** [sparcs-kaist/biseo#229]
![image](https://github.com/sparcs-kaist/biseo/assets/121283722/50f97071-61aa-454e-ad30-23d1d825a829)

**Comment by minjoo0729** [comment]
디자인 부분은 #317에서 핸들 예정이며
버튼 미동작은 개발 완료 되었습니당
