### ISSUE TITLE
[채팅] 이모티콘 버튼 미동작

### ISSUE THREAD

**Issue by jinhyeonkwon** [sparcs-kaist/biseo#232]
마찬가지로 현재 작동해야 하는 버튼인지는 모르고 남기는 피드백입니다. 원래 필요 없는 기능이라면 무시하셔도 됩니다!'
![image](https://github.com/sparcs-kaist/biseo/assets/121283722/cb1dcee6-5bef-416b-971f-9e3fcc7efe98)

**Comment by babycroc** [comment]
헿 기능이 아직 없다

**Comment by SnowSuno** [comment]
전동대회 전 기능 구현 or 버튼 숨기기 중 하나는 해야 할 듯 합니다!

**Comment by withSang** [comment]
<img width="468" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/46402016/37a975e8-71f1-4f75-b87b-66ffed929767">
브라우저에서 OS의 이모티콘 입력창을 바로 띄울 수 있다면 좋을 텐데요.. 👀

**Comment by oganessone718** [comment]
저희 이거 이모티콘 일단 없애기로 하기로 한 것 맞죠?

**Comment by withSang** [comment]
> 저희 이거 이모티콘 일단 없애기로 하기로 한 것 맞죠?

네네!
