### ISSUE TITLE
[투표] 1회 투표 이후 투표하기 버튼이 있으나 동작 없음

### ISSUE THREAD

**Issue by jinhyeonkwon** [sparcs-kaist/biseo#233]
원래 투표 후에 수정이 불가능한 것을 의도하셨다면 무시하셔도 될 것 같습니다!
![image](https://github.com/sparcs-kaist/biseo/assets/121283722/8e4adb61-31d3-481b-b72d-ba2372790221)

**Comment by babycroc** [comment]
수정 불가가 맞아! 근데 버튼 없애야해 그건 이슈 마자 후잉
