### ISSUE TITLE
[UI & 기능 피드백] 지금까지 프로젝트 외부자 입장에서 살펴본 피드백 정리합니다.

### ISSUE THREAD

**Issue by jinhyeonkwon** [sparcs-kaist/biseo#236]
1. 종료된 투표 결과를 항목별로 알려주기 위한 색깔 표시가, 투표에 hover 시 나타나는 색과 같아서 잘 강조되지 않는 것 같습니다.
- hover 색
- 투표 결과를 나타내는 색
- 내 투표를 나타내는 색
위 세 가지가 명확하게 구분되면 더 좋을 것이라고 생각합니다.
![image](https://github.com/sparcs-kaist/biseo/assets/121283722/d1b2efcd-84c5-41b0-ad76-fb580ba69e60)

2. 잘못 만들어진 투표를, 투표한 사람이 없는 경우에는 삭제할 수 있으면 어떨까 합니다. 현재로서는 투표 생성에 실수가 있다면 종료하는 방법 뿐인데, 이 또한 정상적으로 종료된 투표와 함께 기록이 쌓이기 때문에 이를 없애면 깔끔하지 않을까 생각합니다.

3. 투표 관리 탭 쪽에서 뜨는 모달에 들어있는 버튼들이 4K 모니터 기준으로 설정되어 있어서 fullHD 모니터에서 글자가 튀어나가거나 줄바꿈 되는 것으로 추정합니다. 혹시 제가 issue에 미동작이라고 달아둔 버튼이 테스트에서 잘 작동했다면, 같은 이슈일지도 모릅니다. 개인 노트북 모니터로 투표에 참여하는 회원들은 4K보다 작은 해상도를 쓸 가능성도 높으니, 이 문제를 고쳐야 하지 않을까 합니다.

4. 전반적으로 직관적인 UI에, 비서1보다 확장된 기능을 잘 구현한 좋은 결과물이라고 생각합니다! 짧은 시간에 이렇게 개발하시느라 고생 많으셨습니다.

5. 추후에 투표에 태그를 달 수 있다면  (예: 승급 심사 / 회칙 개정 / ...) 어떨까 하는 의견 하나 내 봅니다.

**Comment by minjoo0729** [comment]
꼼꼼한 피드백과 기능 제안 감사합니다 :)
