### ISSUE TITLE
backend min(1) validation이 잘 안됨

### ISSUE THREAD

**Issue by babycroc** [sparcs-kaist/biseo#242]
chat, agenda 등등

**Comment by withSang** [comment]
채팅 max(500)도 안 되는 거죠?? 한 번 살펴볼게요

**Comment by babycroc** [comment]
Max는 안해보긴 했는데 왠지 안될거가타ㅋㅋㅋㅋㅋ

**Comment by withSang** [comment]
@babycroc @SnowSuno 
채팅이랑 agenda 제목에서는 min(1) validation 작동하는 것 같은데 혹시 문제를 어떻게 재현할 수 있을지 궁금해요!
클라이언트에서 의도적으로 빈 문자열을 전송하면 서버 쪽에서 성공적으로(?) 실패해요.

**Comment by babycroc** [comment]
오잉? 어케 테스트했었냐면 프런트 쪽 validation logic 다 지우고 빈 거 보냈을 때 들어가는 것 같던데

**Comment by babycroc** [comment]
아님 백에서 min(10) 이케 하고 더 짧은 거 쳤을 때 보내졌었어

**Comment by babycroc** [comment]
당시에 채팅 인풋만 테스트 해봤었던 걸로 기억해용

**Comment by withSang** [comment]
헉 이따 여러가지 더 테스트해볼게요. 감사합니다 :)
