### ISSUE TITLE
[투표 수정 모달] 유저태그 선택하면 밑에 글자 나타남

### ISSUE THREAD

**Issue by kjy2844** [sparcs-kaist/biseo#249]
디버깅용이었던듯 삭제필요
투표 생성 모달에도 있는지 보고 삭제 필요
<img width="393" alt="스크린샷 2023-08-26 오전 11 48 04" src="https://github.com/sparcs-kaist/biseo/assets/47997136/85d2fb11-3163-4cb5-8437-81caae0f3399">

**Comment by babycroc** [comment]
디버깅용? 맞아요!

**Comment by babycroc** [comment]
어차피 multi select ui에 태그 형식으로 보여주는 게 있어서 그거의 매우매우 시초?? 느낌으로 넣었던거긴해용

**Comment by babycroc** [comment]
Related to #163

**Comment by minjoo0729** [comment]
relate #304
