### ISSUE TITLE
[투표 생성 모달] 투표모드 변경 불가

### ISSUE THREAD

**Issue by 0ev** [sparcs-kaist/biseo#287]
기능인지 버그인지 구분은 잘 가지 않지만 투표 결과와 투표 상세 모드를 변경하는 것이 불가능합니다.
![image](https://github.com/sparcs-kaist/biseo/assets/63383967/66b801c1-c230-4457-a660-508c250a8288)

**Comment by babycroc** [comment]
비서2.0에서는 해당 모드만 지원할 예정이라 변경이 안되는 게 맞아요! 다만 공개로 바꿔야함
