### ISSUE TITLE
[2023 가을 개강 총회] Biseo v2.0 오픈 피드백

### ISSUE THREAD

**Issue by prectal123** [sparcs-kaist/biseo#307]
Biseo v2.0 피드백
--
2023 가을 학기 개강 총회에서 Biseo v2.0을 사용하면서 Biseo에게 주고 싶었던 피드백 혹은 발견한 버그, 이슈 등을 제시해주세요!

코멘트를 통해 이슈를 제시해주시면서, 아래의 양식을 활용해 주세요!

---

이슈 내용: (이슈에 대한 자세한 설명을 제시해주세요)
이슈 종류: **버그** / **기능 불편 사항** / **UI** / **기타**
이슈 위치: **투표** / **어드민** / **채팅** / **기타**
이슈 캡쳐: (선택)

ex)
이슈 내용: 채팅에 입력한 링크를 클릭해도 탭이 열리지 않아요
이슈 종류: 버그
이슈 위치: 채팅

ex)
이슈 내용: 종료된 투표에서 선택지의 득표 수 그래프가 더 선명하면 좋겠어요
이슈 종류: UI
이슈 위치: 투표
이슈 캡쳐: 
![image](https://github.com/sparcs-kaist/biseo/assets/49473889/fb9f752f-05b2-442f-90a1-6f262f21d3ee)

**Comment by withSang** [comment]
이슈 내용: 로그아웃 버튼의 위치를 더 쉽게 알 수 있었으면 좋겠어요. 우측 상단 사용자 아이콘을 눌렀을 때 바로 로그아웃되지 않고, 로그아웃 action이 별도로 표시되면 로그아웃하기 편할 것 같습니다!
이슈 종류: UI
이슈 위치: 기타
이슈 캡쳐: 
<img width="224" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/46402016/7ab1055b-5fd2-4ada-93c3-e2c9e3575382">

**Comment by injoonH** [comment]
와이파이가 좋지 않아 네트워크가 끊기면 새로고침을 해야 소켓 연결을 다시 합니다.

**Comment by 0ev** [comment]
이슈 내용: 투표 수정에서 설명을 수정하면 줄바꿈이 사라집니다.
이슈 종류: 버그
이슈 위치: 투표 수정
