### ISSUE TITLE
채팅 입력에서 사용자에게 글자수 제한 표기 방법

### ISSUE THREAD

**Issue by prectal123** [sparcs-kaist/biseo#309]
채팅창에서 입력되어서 전송될 수 있는 채팅 메세지의 길이를 어떻게 제한할지, 어떻게 사용자에게 알릴지에 관한 이슈입니다.

현재는 채팅을 입력해서 전송할 때, 전송이 되는 것 처럼 보이나 채팅 섹션에 나타나 보이지 않으며, 서버에 적용되지 않습니다.

![image](https://github.com/sparcs-kaist/biseo/assets/49473889/3d0c82f9-55b2-4416-97bd-2f7797e87060)

**Comment by SnowSuno** [comment]
```html
<input max={500} />
```
이와 같은 식으로 설정하면 아예 input안의 텍스트가 500자 이상으로 넘어가지 않아, 원하는 대로 구현할 수 있을 것 같아요

**Comment by withSang** [comment]
오 @SnowSuno 님 아이디어 좋은 것 같아요 
#228 과 같이 해결해보겠습니다.

**Comment by withSang** [comment]
채팅 길이를 시스템적으로 제한하는 것과, 이 제한을 사용자에게 어떻게 보여줄 지 고민하는 것은 다른 이슈인 것 같아요.
제 PR과 연결된 것을 끊겠습니다.

**Comment by SnowSuno** [comment]
글자수 제한에 대해서는 클라이언트 인풋에서 더 입력되지 않도록 하는 것으로 충분하다고 생각해서
추가적으로 더 다른 정보를 보여줄 필요는 없을 것 같습니다. 

slack, 카카오톡 등도 모두 비슷한 방식을 사용하는 것으로 알고 있습니당
