### ISSUE TITLE
종료된 투표 중복으로 보여짐

### ISSUE THREAD

**Issue by minjoo0729** [sparcs-kaist/biseo#349]
# 이슈 내용 \*
from #307 
종료된 투표가 중복되서 나오는것 같습니다

## 스크린샷
![image](https://github.com/sparcs-kaist/biseo/assets/114305937/c77e83c7-0bef-4814-83cb-e0faab43560f)

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by JeukHwang** [comment]
오 혹시 더블 클릭 때문일까요?

**Comment by SnowSuno** [comment]
혹시 이거 재현되시는 분 있나요?

**Comment by SnowSuno** [comment]
#384 에서 고쳐진 것 같아요
