### ISSUE TITLE
투표/템플릿/유저 태그 생성 시 최대 글자 수 제한 (client side)

### ISSUE THREAD

**Issue by withSang** [sparcs-kaist/biseo#375]
# 제안 내용 \*

아래 이벤트들의 입력값 검증(string; 최대 255자)을 input 태그들에 추가합니다.
	- `admin.agenda.create`
	- `agenda.template.create`
	- `user.tag.create`

## 스크린샷

없음.

# 관련 Task \*

- [x] `admin.agenda.create`에서 최대 글자 수 제한
- [x] `agenda.template.create`에서 최대 글자 수 제한
- [x] `user.tag.create`에서 최대 글자 수 제한

**Comment by JeukHwang** [comment]
`admin.agenda.create` 같은 update 관련 query도 검증이 필요할 것 같습니다.
또한 한 query에서도 투표 제목 길이, 개별 선택지 길이, 선택지 개수 제한 등 여러 숫자가 있음을 감안해야 하지 않을까 싶습니다.
