### ISSUE TITLE
커밋 시 error: cannot spawn .git/hooks/pre-commit: No such file or directory 오류

### ISSUE THREAD

**Issue by rjsdn0** [sparcs-kaist/biseo#391]
# 이슈 내용 \*

git commit 시 error: cannot spawn .git/hooks/pre-commit: No such file or directory 오류가 발생하며 커밋이 되지 않음

## 스크린샷

![image](https://github.com/sparcs-kaist/biseo/assets/144145159/07c9b343-4c44-4d23-be4b-82f1338557aa)

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by withSang** [comment]
관련 슬랙 논의: https://sparcs.slack.com/archives/C01RC6QMSL8/p1695133046551119?thread_ts=1695133046.551119&cid=C01RC6QMSL8
