### ISSUE TITLE
[UI] 보내기 버튼 위치

### ISSUE THREAD

**Issue by oganessone718** [sparcs-kaist/biseo#403]
# 이슈 내용 \*

보내기 버튼이 중앙 정렬이 안 되어 있는 것 같습니다.
이미 있던 이슈이거나 의도적인 거면 무시해주세요 ㅜㅜ!

## 스크린샷
![image](https://github.com/sparcs-kaist/biseo/assets/105881036/26586a29-3650-45f2-8248-4a920fa82911)
<img width="377" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/105881036/c20c7379-1490-4367-a462-b5ebb18a84a5">

**Comment by babycroc** [comment]
오 저거는 내가 피그마를 보니까 아이콘 frame 크기가 뭔가 통일이 안되어 있는 것 같아서 피그마 정리하면서 해야하긴 할 것 같은디 
이슈로 남겨놓는 건 좋은 것 같아요

**Comment by withSang** [comment]
제일 마지막으로 건든 사람이 저였군요 ㅋㅋㅋㅋㅋㅋㅋㅋ... 죄송합니다...
