### ISSUE TITLE
border color 변경

### ISSUE THREAD

**Issue by minjoo0729** [sparcs-kaist/biseo#416]
# 이슈 내용 \*
<1024 회의 중>
선택된 종료 투표 컴포넌트 border color 수정 필요

## 스크린샷

# 관련 Task \*

- [ ] Task1
- [ ] Task2

**Comment by Sanghou** [comment]
https://github.com/sparcs-kaist/biseo/pull/424

여기서 처리된 것으로 확인되어 close합니다
