### ISSUE TITLE
종료된 투표 시간에 대해 내림차순 정렬

### ISSUE THREAD

**Issue by SnowSuno** [sparcs-kaist/biseo#450]
# 제안 내용 \*

이슈 내용: 종료된 투표 시간에 대해 내림차순 필요 (가장 최근에 한 투표가 제일 위로 가게),  그리고 지난 회의 때 종료된 투표와 당일 종료된 투표를 디자인으로 구분지어줘도 좋을 것 같기두

## 스크린샷
<img width="351" alt="스크린샷 2023-11-27 오후 9 54 11" src="https://github.com/sparcs-kaist/biseo/assets/88485008/78eeac19-52e7-4c44-ac40-85abaca54f8f">

# 관련 Task \*

- [ ] 내림차순 정렬

**Comment by Sanghou** [comment]
해당 기능 질문 있어요!
- 클라이언트에서 정렬해주는 것과 서버에서 정렬된 값을 내려주는 것 2가지가 있을텐데 서버에서 정렬해서 내려줘야 할까요?
