### ISSUE TITLE
채팅 보내기 버튼 상하 정렬

### ISSUE THREAD

**Issue by rjsdn0** [sparcs-kaist/biseo#466]
# 이슈 내용 \*

채팅 보내기 아이콘이 상하정렬이 안되어있습니다!

## 스크린샷

![image](https://github.com/sparcs-kaist/biseo/assets/144145159/0dce14ea-5368-49d1-818d-5d70b149e263)

**Comment by yumincho** [comment]
같은 이슈가 https://github.com/sparcs-kaist/biseo/issues/403에 레포트되어 있는 것 같습니다. 그리고 https://github.com/sparcs-kaist/biseo/pull/470 PR에서 이를 해결해 두었습니다 👍

**Comment by rjsdn0** [comment]
확인 했습니다! 이슈 닫아놓을게용
