### ISSUE TITLE
admin 페이지 대기중인 투표 display card 만들기

### ISSUE THREAD

**Issue by donghyo1234** [sparcs-kaist/biseo#48]
admin 페이지의 대기 중인 투표 display card 만들겁니다

**Comment by kjy2844** [comment]
<img width="354" alt="스크린샷 2023-08-15 오전 12 18 01" src="https://github.com/sparcs-kaist/biseo/assets/47997136/fd172524-8a1f-42f5-92a3-3a5bcf7df7b4">
