### ISSUE TITLE
아젠다 오픈 시 투표 제목이 길면 날짜 스타일이 깨짐

### ISSUE THREAD

**Issue by yumincho** [sparcs-kaist/biseo#489]
# 이슈 내용 \*

투표 제목이 긴 경우, 아젠다 카드를 열었을 때 스타일이 깨집니다

## 스크린샷
<img width="376" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/100757008/90ab6205-da81-4b08-aeb5-cec91857c40c">

# 관련 Task \*

- [ ] 투표 제목, 날짜 위치 조정

**Comment by rjsdn0** [comment]
[https://github.com/sparcs-kaist/biseo/pull/493](url)
위 PR에서 새로운 디자인으로 수정하면서 해결된것 같아요!
이슈 닫겠습니다!
