### ISSUE TITLE
모달 focus 관련 버그

### ISSUE THREAD

**Issue by babycroc** [sparcs-kaist/biseo#64]
# 이슈 내용
- 모달 열면 x버튼 focus 됨
- esc 누르면 url 안 바뀌어도 모달 닫힘
=> 모달을 dialog 아닌 div로 바꿔야할 것 같아요

# 관련 Task

- [x] dialog에서 div로 변경
- [x] 외부 클릭 시 모달 닫기
- [x] 모달 열면 첫 input 요소 focus하기
- [x] 모달 띄워졌을 때 스크롤 방지
~Esc 키 누르면 모달 닫기~ -> 텍스트 필드 입력 중 esc 키를 누르면 모달이 닫힐 수 있어 구현하지 않았습니다.
- [x] css 토큰화

**Comment by SnowSuno** [comment]
url 바뀌는건 dialog.onclose` 같은거로 해결할수 있긴 한데...
어차피 backdrop 문제도 있고 해서 div으로 구현하는거 나쁘지않은거같아요

**Comment by withSang** [comment]
react-select에서 드롭다운 옵션도 modal이 dialog라서 위에 표시가 안 되는 문제가 있네요..ㅠ div로 고쳐야겠어요

**Comment by babycroc** [comment]
그런거엿군요(?) ㄴㅇㄱ
